#!/bin/bash
# Recreate void-test-linux with Ubuntu 24.04 LTS autoinstall (NoCloud CIDATA).
# Run on Unraid (lightfootserver) as root.
#
# Why rewrite: previous guest used EOL Ubuntu 23.10 desktop ISO; Subiquity failed
# at "configuring apt"; vdisk stayed empty (~4 KiB). Manual VNC install is fragile.
#
# Requires: curl/wget, qemu-img, mkfs.vfat, python3, virsh (no virt-install/xorriso needed).
set -euo pipefail

NAME="${VOID_LINUX_VM_NAME:-void-test-linux}"
VM_ROOT="${VOID_VM_ROOT:-/mnt/user/VMs}"
ISO_DIR="${VOID_ISO_DIR:-/mnt/user/isos/test}"
NVRAM_DIR="/etc/libvirt/qemu/nvram"
OVMF_CODE="/usr/share/qemu/ovmf-x64/OVMF_CODE-pure-efi.fd"
OVMF_VARS="/usr/share/qemu/ovmf-x64/OVMF_VARS-pure-efi.fd"

# Ubuntu 24.04.2 LTS live-server (autoinstall-friendly). Override with VOID_UBUNTU_ISO.
UBUNTU_ISO_URL="${VOID_UBUNTU_ISO_URL:-https://releases.ubuntu.com/24.04.2/ubuntu-24.04.2-live-server-amd64.iso}"
UBUNTU_ISO="${VOID_UBUNTU_ISO:-$ISO_DIR/ubuntu-24.04.2-live-server-amd64.iso}"

HOSTNAME="${VOID_LINUX_HOSTNAME:-rpa-linux-vm}"
USERNAME="${VOID_LINUX_USER:-rpa-linux}"
# Prefer existing host secret file; else VOID_LINUX_PASS env; else generate once.
CREDS_FILE="${VOID_CREDS_FILE:-/root/void-rpa-vm-credentials.txt}"

DISK_GIB="${VOID_LINUX_DISK_GIB:-40}"
RAM_KIB="${VOID_LINUX_RAM_KIB:-4194304}"   # 4 GiB — enough for desktop + cargo; host is RAM-tight
VCPUS="${VOID_LINUX_VCPUS:-4}"
MAC="${VOID_LINUX_MAC:-52:54:00:76:6f:69}"

DIR="$VM_ROOT/$NAME"
DISK="$DIR/vdisk1.img"
CIDATA="$DIR/cidata.img"
SEED_DIR="$DIR/seed"

die() { echo "ERROR: $*" >&2; exit 1; }

need() { command -v "$1" >/dev/null 2>&1 || die "missing command: $1"; }

need virsh
need qemu-img
need python3
need mkfs.vfat
need curl
test -f "$OVMF_CODE" || die "missing $OVMF_CODE"
test -f "$OVMF_VARS" || die "missing $OVMF_VARS"

mkdir -p "$DIR" "$ISO_DIR" "$NVRAM_DIR" "$SEED_DIR"

resolve_password() {
  if [[ -n "${VOID_LINUX_PASS:-}" ]]; then
    printf '%s' "$VOID_LINUX_PASS"
    return
  fi
  if [[ -f "$CREDS_FILE" ]]; then
    local pass
    pass=$(CREDS_FILE="$CREDS_FILE" python3 - <<'PY'
from pathlib import Path
import os
text = Path(os.environ["CREDS_FILE"]).read_text()
# Prefer Pass: under the Linux VM section
in_linux = False
for line in text.splitlines():
    low = line.lower()
    if "linux vm" in low or "void-test-linux" in low:
        in_linux = True
    if in_linux and low.strip().startswith("pass:"):
        print(line.split(":", 1)[1].strip())
        raise SystemExit
# fallback: first Pass: after any linux mention
seen = False
for line in text.splitlines():
    if "linux" in line.lower():
        seen = True
    if seen and line.lower().strip().startswith("pass:"):
        print(line.split(":", 1)[1].strip())
        raise SystemExit
PY
)
    if [[ -n "$pass" ]]; then
      printf '%s' "$pass"
      return
    fi
  fi
  local gen
  gen=$(python3 -c 'import secrets,string; a=string.ascii_letters+string.digits; print("".join(secrets.choice(a) for _ in range(20)))')
  umask 077
  {
    echo ""
    echo "# $(date -Iseconds) auto-generated by unraid-recreate-void-test-linux.sh"
    echo "Linux VM: void-test-linux (hostname $HOSTNAME)"
    echo "  User: $USERNAME"
    echo "  Pass: $gen"
  } >> "$CREDS_FILE"
  chmod 600 "$CREDS_FILE"
  echo "Generated Linux password → $CREDS_FILE" >&2
  printf '%s' "$gen"
}

echo "=== 1) Ensure Ubuntu 24.04 live-server ISO ==="
if [[ ! -f "$UBUNTU_ISO" ]]; then
  echo "Downloading $UBUNTU_ISO_URL ..."
  curl -fL --retry 3 -o "$UBUNTU_ISO.partial" "$UBUNTU_ISO_URL"
  mv "$UBUNTU_ISO.partial" "$UBUNTU_ISO"
fi
ls -lh "$UBUNTU_ISO"

PASS=$(resolve_password)
# SHA-512 hash for autoinstall identity.password (openssl; works on Unraid)
PASS_HASH=$(OPENSSL_PASS="$PASS" python3 - <<'PY'
import os, subprocess
p = os.environ["OPENSSL_PASS"]
out = subprocess.check_output(["openssl", "passwd", "-6", p], text=True).strip()
print(out)
PY
)

echo "=== 2) Stop / undefine existing $NAME ==="
if virsh dominfo "$NAME" >/dev/null 2>&1; then
  STATE=$(virsh domstate "$NAME" 2>/dev/null || true)
  if [[ "$STATE" == "running" ]]; then
    virsh destroy "$NAME" || true
  fi
  virsh undefine "$NAME" --nvram 2>/dev/null || virsh undefine "$NAME" || true
fi

echo "=== 3) Recreate empty disk + CIDATA seed ==="
rm -f "$DISK" "$CIDATA"
qemu-img create -f raw "$DISK" "${DISK_GIB}G"
qemu-img create -f raw "$CIDATA" 2M
mkfs.vfat -n CIDATA "$CIDATA"

# meta-data / user-data for Ubuntu autoinstall (Subiquity)
cat > "$SEED_DIR/meta-data" <<EOF
instance-id: ${NAME}-001
local-hostname: ${HOSTNAME}
EOF

# Autoinstall + first-boot packages for desktop tooling / SSH / guest agent.
# Write via Python so SHA-512 $6$ hashes are not expanded by the shell.
HOSTNAME="$HOSTNAME" USERNAME="$USERNAME" PASS_HASH="$PASS_HASH" SEED_DIR="$SEED_DIR" python3 - <<'PY'
import os
from pathlib import Path
hostname = os.environ["HOSTNAME"]
username = os.environ["USERNAME"]
pw = os.environ["PASS_HASH"]
seed = Path(os.environ["SEED_DIR"])
pw_yaml = "'" + pw.replace("'", "''") + "'"
body = f"""#cloud-config
autoinstall:
  version: 1
  locale: en_US.UTF-8
  keyboard:
    layout: us
  identity:
    hostname: {hostname}
    username: {username}
    password: {pw_yaml}
  ssh:
    install-server: true
    allow-pw: true
  storage:
    layout:
      name: direct
  # Skip slow in-installer security upgrade; first-boot cloud-init can apt update.
  updates: none
  network:
    version: 2
    ethernets:
      enp1s0:
        dhcp4: true
  packages:
    - qemu-guest-agent
    - openssh-server
    - curl
    - git
  user-data:
    package_upgrade: false
    packages:
      - ubuntu-desktop-minimal
      - qemu-guest-agent
      - build-essential
      - pkg-config
      - libwebkit2gtk-4.1-dev
      - libgtk-3-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - libssl-dev
    runcmd:
      - systemctl enable --now ssh
      - systemctl enable --now qemu-guest-agent
      - timedatectl set-ntp true
  late-commands:
    - curtin in-target --target=/target -- systemctl enable ssh
    - curtin in-target --target=/target -- systemctl enable qemu-guest-agent
"""
(seed / "user-data").write_text(body)
print("Wrote", seed / "user-data")
PY

# Copy seed files into FAT volume
MNT=$(mktemp -d)
mount -o loop "$CIDATA" "$MNT"
cp "$SEED_DIR/user-data" "$SEED_DIR/meta-data" "$MNT/"
# Ubuntu also accepts vendor-data empty
touch "$MNT/vendor-data"
sync
umount "$MNT"
rmdir "$MNT"
echo "CIDATA ready: $CIDATA"

UUID=$(uuidgen)
NVRAM="$NVRAM_DIR/${UUID}_VARS-pure-efi.fd"
cp "$OVMF_VARS" "$NVRAM"

# Kernel cmdline for autoinstall — injected via SMBIOS serial / or boot from ISO with kernel args.
# Live-server reads NoCloud from a disk labeled CIDATA automatically when present.
# Also pass autoinstall via fw_cfg / QEMU -smbios for reliability:
# We use libvirt <qemu:commandline> sparingly; instead rely on CIDATA + GRUB edit is NOT automated.
# Best approach on Unraid without virt-install: use a tiny "autoinstall" boot by editing
# the ISO is hard. Alternative: use kernel/initrd extract + direct kernel boot.
#
# Direct kernel boot from the ISO (casper) with autoinstall args:

echo "=== 4) Extract kernel/initrd from live-server ISO ==="
ISO_MNT=$(mktemp -d)
mount -o loop,ro "$UBUNTU_ISO" "$ISO_MNT"
KERNEL="$DIR/vmlinuz"
INITRD="$DIR/initrd"
cp "$ISO_MNT/casper/vmlinuz" "$KERNEL"
# Ubuntu 24.04 uses initrd named initrd (not initrd.lz)
if [[ -f "$ISO_MNT/casper/initrd" ]]; then
  cp "$ISO_MNT/casper/initrd" "$INITRD"
elif [[ -f "$ISO_MNT/casper/initrd.lz" ]]; then
  cp "$ISO_MNT/casper/initrd.lz" "$INITRD"
else
  ls -la "$ISO_MNT/casper/" >&2
  umount "$ISO_MNT"
  die "could not find casper initrd on ISO"
fi
umount "$ISO_MNT"
rmdir "$ISO_MNT"
ls -lh "$KERNEL" "$INITRD"

# Direct kernel boot: install to disk, then on first reboot use disk boot (XML rewritten by finish script).
# For initial define we use <os><kernel> autoinstall ...
CMDLINE="autoinstall ds=nocloud;s=/ cidata cloud-config-url=/dev/null console=ttyS0,115200n8 console=tty1 ---"

echo "=== 5) Define domain (direct kernel autoinstall) ==="
cat > "/tmp/${NAME}.xml" <<EOF
<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
  <name>${NAME}</name>
  <uuid>${UUID}</uuid>
  <description>Void Browser Linux RPA/test — Ubuntu 24.04 autoinstall</description>
  <metadata>
    <vmtemplate xmlns="unraid" name="Ubuntu" icon="ubuntu.png" os="ubuntu" webui="" storage="default"/>
  </metadata>
  <memory unit='KiB'>${RAM_KIB}</memory>
  <currentMemory unit='KiB'>${RAM_KIB}</currentMemory>
  <memoryBacking>
    <nosharepages/>
  </memoryBacking>
  <vcpu placement='static'>${VCPUS}</vcpu>
  <os>
    <type arch='x86_64' machine='pc-q35-8.0'>hvm</type>
    <loader readonly='yes' type='pflash' format='raw'>${OVMF_CODE}</loader>
    <nvram format='raw'>${NVRAM}</nvram>
    <kernel>${KERNEL}</kernel>
    <initrd>${INITRD}</initrd>
    <cmdline>autoinstall ds=nocloud cloud-config-url=/dev/null console=ttyS0,115200n8 console=tty1 ---</cmdline>
  </os>
  <features>
    <acpi/>
    <apic/>
  </features>
  <cpu mode='host-passthrough' check='none' migratable='on'>
    <topology sockets='1' dies='1' clusters='1' cores='2' threads='2'/>
  </cpu>
  <clock offset='utc'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>destroy</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <emulator>/usr/local/sbin/qemu</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw' cache='writeback' discard='unmap'/>
      <source file='${DISK}'/>
      <target dev='vda' bus='virtio'/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw'/>
      <source file='${CIDATA}'/>
      <target dev='vdb' bus='virtio'/>
    </disk>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <source file='${UBUNTU_ISO}'/>
      <target dev='sda' bus='sata'/>
      <readonly/>
    </disk>
    <controller type='usb' index='0' model='qemu-xhci'/>
    <controller type='sata' index='0'/>
    <controller type='virtio-serial' index='0'/>
    <controller type='pci' index='0' model='pcie-root'/>
    <interface type='bridge'>
      <mac address='${MAC}'/>
      <source bridge='br0'/>
      <model type='virtio'/>
    </interface>
    <serial type='pty'>
      <target type='isa-serial' port='0'/>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <channel type='unix'>
      <target type='virtio' name='org.qemu.guest_agent.0'/>
    </channel>
    <input type='tablet' bus='usb'/>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
    <graphics type='vnc' port='-1' autoport='yes' websocket='-1' listen='0.0.0.0' keymap='en-us' sharePolicy='ignore'>
      <listen type='address' address='0.0.0.0'/>
    </graphics>
    <audio id='1' type='none'/>
    <video>
      <model type='qxl' ram='65536' vram='65536' vgamem='16384' heads='1' primary='yes'/>
    </video>
    <memballoon model='virtio'/>
  </devices>
</domain>
EOF

virsh define "/tmp/${NAME}.xml"
virsh start "$NAME"

echo
echo "=== Installer started ==="
echo "VNC: check with: virsh vncdisplay $NAME"
echo "Serial: virsh console $NAME"
echo "Password for $USERNAME is in $CREDS_FILE (not printed here)."
echo
echo "After autoinstall finishes the domain destroys on reboot (on_reboot=destroy)."
echo "Then run: bash scripts/unraid-finalize-void-test-linux.sh"
echo "Or this script's companion will poll and finalize."
echo "DONE start"
